packages:
  - .

minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
blockExoticSubdeps: true
strictDepBuilds: true
autoInstallPeers: false
engineStrict: true
ignoreScripts: true
strictPeerDependencies: true
verifyDepsBeforeRun: error
savePrefix: ""

overrides:
  semver: 7.7.2
